apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: retail-sc
  namespace: murali-ns
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
parameters:
  type: gp2
